version: '3'
services :
  app:
    container_name: video_lib
    build: .
    restart: unless-stopped
    volumes:
     - ./:/video_library
    command: sh -cx "python manage.py makemigrations && 
        python manage.py migrate && 
        python manage.py collectstatic --noinput && 
        python manage.py runserver  0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
    ports:
      - "127.0.0.1:6565:8000"

  db:
    container_name: videolib_db
    image: postgres
    restart: unless-stopped 
    ports:
      - "5422:5432"
    env_file:
      - .env
##    volumes:
##      - db-storage:/var/lib/postgresql/data
##    deploy:
##      resources:
##        limits:
##          memory: 14G

