# -*- coding: utf-8 -*-
messages = {
    114: "Unable to process the request at this time, please try again later.",
    200: "Ok",
    201: "Created.",
    202: "Account already verified.",
    204: "No Records found",
    205: "Invalid or Expired otp",
    206: "Invalid or Expired link",
    250: "Information does not exist. Might have been already deleted.",
    301: "Phone number cannot be null or empty.",
    302: "First name  cannot be null or empty.",
    303: "Last name  cannot be null or empty.",
    304: "Username cannot be null or empty.",
    305: "Password cannot be null or empty.",
    306: "Search value cannot be null or empty.",
    307: "Email cannot be null or empty.",
    308: "User id cannot be null or empty.",
    309: "Video not found",
    311: "Cannot use previous password.Please try with new password.",
    313: "Error in upload.",
    314: "Select an user other than you.",
    315: "Phone number cannot be null or empty",
    400: "Bad request",
    401: "Unauthorized token",
    403: "Forbidden.",
    403_1: "Permission denied. Users should be Admin",
    403_2: "Permission denied. Users should be Admin/editor",
    404: "Not Found.",
    410: "Token cannot be empty.",
    500: "Internal Server Error.",
    501: "Invalid User.",
    502: "Inactive User.",
    503: "Login Failed. Username or password is incorrect.",
    504: "Refresh token cannot be empty.",
    505: "Not Refresh Token.",
    506: "Expired or Invalid Token.",
    507: "DB connection failed",
    518: "An email is sent to your registered email address with a link to reset your password.",
    519: "An email is sent to your registered email address with a OTP to activate account",
    600: "Validation failed.",
    604: "Email is not valid.",
    617: "Multiple failed login attempts have been detected on your account.  Your account has been temporarily "
    "locked. Please try logging in again after 5 hours.",
    618: "Password doesn't match the criteria.",
    619: "Current Password does not match with previous one.",
    620: "File extension not allowed ",
    621: "Email is already registered, try another Email.",
    622: "Not allowed",
    706: "Phone number is not valid",
    707: "Invalid language",
    708: "file write failed",
    709: "mandatory upload fields missing",
    710: "failed to insert data to DB",
    711: "keyword priority should not be empty",
    712: "connection established successfully",
    713: "any one of the process must be selected",
    714: "data already in db or invalid data insertion",
    715: "invalid data format",
}


def get_message(code):
    message = messages[code]
    return message
